### ISSUE TITLE
I  can't get the screen

### ISSUE THREAD

**Issue by lfjking** [nwlunatic/ios-minicap#22]
status:
`
$ ./run.sh
\++ system_profiler SPUSBDataType
\++ sed -n -E -e '/(iPhone|iPad)/,/Serial/s/ *Serial Number: *(.+)/\1/p'
\+ UDID=ff..........e7
\+ PORT=12345
\+ RESOLUTION=400x600
\+ ./build/ios_minicap --udid ff..........e7 --port 12345 --resolution 400x600
EnableDALDevices
2017-06-05 18:05:29.306 ios_minicap[1829:1343756] Available devices:
2017-06-05 18:05:29.315 ios_minicap[1829:1343756] ff..........e7 

`

the app status:
`
$ node app.js
Listening on port 9002
Got a client
{ Error: connect ECONNREFUSED 127.0.0.1:12345
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 12345 }
Be sure to run ios-minicap on port 12345
`
the localhost:9002 have not screen.
what wrong with this?

**Comment by RanjithkumarRagavan** [comment]
@lfjking Are you able to resolve this issue?

**Comment by sorccu** [comment]
Make sure the display is on. Otherwise it gets stuck at that point.

**Comment by Rootjhon** [comment]
run ./run.sh then wait unitl show banner,then run node app.js.try it
