### ISSUE TITLE
start app.js failed

### ISSUE THREAD

**Issue by likezjuisee** [nwlunatic/ios-minicap#30]
const { Parser } = require('minicap')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3

**Comment by sorccu** [comment]
Your node is too old and we stopped caring about older versions.
