### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by likezjuisee** [nwlunatic/ios-minicap#31]
++ system_profiler SPUSBDataType
++ sed -n -E -e '/(iPhone|iPad)/,/Serial/s/ *Serial Number: *(.+)/\1/p'
+ UDID=b2095a48b0df41cdd338297e1e11e6a81b7b0173
+ PORT=12345
+ RESOLUTION=400x600
+ ./build/ios_minicap --udid b2095a48b0df41cdd338297e1e11e6a81b7b0173 --port 12345 --resolution 400x600
EnableDALDevices
2017-10-02 10:24:10.937 ios_minicap[72393:178530] Available devices:
2017-10-02 10:24:10.939 ios_minicap[72393:178530] b2095a48b0df41cdd338297e1e11e6a81b7b0173
2017-10-02 10:24:10.939 ios_minicap[72393:178530] 0x1a11000005ac8509

localhost:example like$ node app.js 
Listening on port 9002
Got a client
{ Error: connect ECONNREFUSED 127.0.0.1:12345
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 12345 }
Be sure to run ios-minicap on port 12345

**Comment by toaddeven** [comment]
set ipv4 connect
![image](https://user-images.githubusercontent.com/58658432/231793504-054a350a-3e61-4df7-9171-ef3350d8d09e.png)
