### ISSUE TITLE
Could not start Example 

### ISSUE THREAD

**Issue by serhatbolsu** [nwlunatic/ios-minicap#8]
I have started ios-minicap (I believe) however could not start the example.

Mac $ node app.js
/Users/serhatbolsu/Downloads/ios-minicap-master/example/app.js:8
const { BannerParser, FrameParser } = require('minicap')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

Thank you for this addition, will be great when it has parallel record support

**Comment by sorccu** [comment]
Your node is too old and we don't support it. Use at least v6.
